name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install libs
        run: |
          forge install foundry-rs/forge-std --no-git
          forge install OpenZeppelin/openzeppelin-contracts --no-git
          forge install OpenZeppelin/openzeppelin-contracts-upgradeable --no-git
          forge install smartcontractkit/chainlink-brownie-contracts --no-git

      - name: Build
        run: forge build --sizes

      - name: Test
        run: forge test -vv

      - name: Coverage
        run: forge coverage --report summary --no-match-coverage "(script|test)/.*"

  slither:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install libs
        run: |
          forge install foundry-rs/forge-std --no-git
          forge install OpenZeppelin/openzeppelin-contracts --no-git
          forge install OpenZeppelin/openzeppelin-contracts-upgradeable --no-git
          forge install smartcontractkit/chainlink-brownie-contracts --no-git

      - name: Slither
        uses: crytic/slither-action@v0.4.0
        with:
          fail-on: high
          slither-config: slither.config.json
